lldb: Explicitly include <cstdint>
GCC 15 will no longer include it by default, resulting in build
failures in projects that do not explicitly include it.

Error:
In file included from lldb/source/Utility/AddressableBits.cpp:9:
lldb/include/lldb/Utility/AddressableBits.h:25:27: error: ‘uint32_t’ has not been declared
   25 |   void SetAddressableBits(uint32_t addressing_bits);
      |                           ^~~~~~~~
lldb/include/lldb/Utility/AddressableBits.h:29:27: error: ‘uint32_t’ has not been declared
   29 |   void SetAddressableBits(uint32_t lowmem_addressing_bits,
      |                           ^~~~~~~~
lldb/include/lldb/Utility/AddressableBits.h:30:27: error: ‘uint32_t’ has not been declared
   30 |                           uint32_t highmem_addressing_bits);
      |                           ^~~~~~~~
lldb/include/lldb/Utility/AddressableBits.h:32:33: error: ‘uint32_t’ has not been declared
   32 |   void SetLowmemAddressableBits(uint32_t lowmem_addressing_bits);
      |                                 ^~~~~~~~
lldb/include/lldb/Utility/AddressableBits.h:34:34: error: ‘uint32_t’ has not been declared
   34 |   void SetHighmemAddressableBits(uint32_t highmem_addressing_bits);
      |                                  ^~~~~~~~
lldb/include/lldb/Utility/AddressableBits.h:39:3: error: ‘uint32_t’ does not name a type
   39 |   uint32_t m_low_memory_addr_bits;
      |   ^~~~~~~~
lldb/include/lldb/Utility/AddressableBits.h:13:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   12 | #include "lldb/lldb-forward.h"
  +++ |+#include <cstdint>
   13 |
lldb/include/lldb/Utility/AddressableBits.h:40:3: error: ‘uint32_t’ does not name a type
   40 |   uint32_t m_high_memory_addr_bits;
      |   ^~~~~~~~
lldb/include/lldb/Utility/AddressableBits.h:40:3: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’

See-also: https://gcc.gnu.org/pipermail/gcc-cvs/2024-August/407124.html
See-also: https://bugs.gentoo.org/937425
Signed-off-by: Paul Zander <negril.nx+gentoo@gmail.com>